CREATE TABLE usuario(
usuario_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(45) NOT NULL,
apellido VARCHAR(45) NOT NULL,
nick VARCHAR(45) NOT NULL UNIQUE,
contraseña VARCHAR(45) NOT NULL,
correo VARCHAR(45) NOT NULL UNIQUE,
estado INT(5) NOT NULL,
create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE setup(
setup_id INTEGER PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(45) NOT NULL,
estado INT(5) DEFAULT 0,
conciencia VARCHAR(5) DEFAULT 'no', #carga preguntas y respuestas
usuario VARCHAR(60) NOT NULL,
create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat(
chat_id INTEGER PRIMARY KEY AUTO_INCREMENT,
pregunta VARCHAR(255) NULL,
respuesta VARCHAR(255) DEFAULT 0,
pesos FLOAT(255) DEFAULT 0,
estado int(10) DEFAULT 0,
create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat_repeticiones(
chat_id INTEGER PRIMARY KEY AUTO_INCREMENT,
pregunta VARCHAR(255) NULL,
respuesta VARCHAR(255) DEFAULT 0,
veces_repetida FLOAT(255) DEFAULT 0,
estado int(10) DEFAULT 0,
create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

#SI LA PREGUNTA NO TIENE RESPUESTA AL RESPONDE

CREATE TABLE sistema(
sistema_id INTEGER PRIMARY KEY AUTO_INCREMENT,
pregunta VARCHAR(255) NOT NULL,
respuesta VARCHAR(255) NOT NULL,
estado int(10) DEFAULT 0,
create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);